---
title: "Does asthma increase the risk of CVD? A Mendelian Randomization analysis"
author: "Carlos A. Valencia-Hernández"
date: '2022-06-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Does asthma increase the risk of CVD? A Mendelian Randomization analysis


```{r}
library(MendelianRandomization)
#Including the data from tables 2 and 3 from Laura's report

snpchd <- c(-0.013709, 0.0284218, -0.0147016, -0.00333015, 
            -0.0613769, 0.00693918, 0.00354782, 0.00686334, 
            -0.00984722, 0.0116513, -0.00491, 0.0326155, 
            -0.0294908, -0.00935933, 0.0083816, 0.00893951)

snpchdse <- c(0.0111191,0.0141726, 0.0112911, 0.0110223,
              0.0110725, 0.0122976, 0.0138886, 0.0113783,
              0.0136261, 0.0110918, 0.0112812, 0.0139859,
              0.011111, 0.0124713, 0.0110746, 0.0116967)


snpasth <- c(-0.05424, -0.058903, 0.0854639, -0.0791631,
             -0.0635335, -0.0745456, 0.114988, 0.0738917,
             0.0946258, -0.106916, -0.0989991, 0.179604,
             -0.167699, 0.140973, -0.095609, 0.0896441)

snpasthse <- c(0.00724845, 0.00908744, 0.00737088, 0.0071452,
               0.00720572, 0.00792657, 0.00889454, 0.00737473,
               0.00894163, 0.00719124, 0.0072996, 0.107546, 
               0.00728578, 0.00799402, 0.0071734, 0.00755048) 


```


```{r}
mr_ivw(mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse)) 

mr_ivw(mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse))$Estimate 

mr_ivw(mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse), robust=TRUE)

mr_ivw(mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse), penalized = TRUE)

mr_ivw(mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse), robust=TRUE, 
       penalized = TRUE)

mr_ivw(mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse), 
model = "fixed", alpha = 0.01, distribution = "t-dist")

MRdata_ASTH_CHD <- mr_input(bx=snpchd, bxse=snpchdse, by=snpasth, byse=snpasthse)

print(MRdata_ASTH_CHD)

```




```{r, echo=FALSE}

mr_plot(mr_allmethods(MRdata_ASTH_CHD,
              method ="main"))
```


```{r, echo=FALSE}

mr_plot(MRdata_ASTH_CHD)

```



